version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: uaifood-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: uaifood
      POSTGRES_PASSWORD: uaifood
      POSTGRES_DB: uaifood
    ports:
      - '55432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U uaifood']
      interval: 5s
      retries: 10
      timeout: 5s
volumes:
  dbdata:
